const INITIAL_MOVIES = [
  {
    imdbID: "tt1",
    Title: "Jawan",
    Year: "2023",
    Rated: "UA",
    Released: "07 Sep 2023",
    Runtime: "169 min",
    Genre: "Action, Thriller",
    Director: "Atlee",
    Writer: "Atlee, Ramanagirivasan",
    Actors: "Shah Rukh Khan, Nayanthara, Vijay Sethupathi",
    Plot: "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
    Language: "Hindi",
    Country: "India",
    Awards: "14 wins & 22 nominations",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3giEteXGggow1hYtpRIuy3bDLO_Z9aoximYp_tuFK0Bb0N_fnmPaChKv1l_mgBxiiOwN3&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "7.1/10" }],
    imdbRating: "7.1",
    Type: "movie",
    BoxOffice: "$135,000,000"
  },
  {
    imdbID: "tt2",
    Title: "Pathaan",
    Year: "2023",
    Rated: "UA",
    Released: "25 Jan 2023",
    Runtime: "146 min",
    Genre: "Action, Adventure, Thriller",
    Director: "Siddharth Anand",
    Writer: "Shridhar Raghavan, Abbas Dalal, Siddharth Anand",
    Actors: "Shah Rukh Khan, Deepika Padukone, John Abraham",
    Plot: "An Indian spy takes on the leader of a group of mercenaries who have nefarious plans to target his homeland.",
    Language: "Hindi",
    Country: "India",
    Awards: "14 wins & 23 nominations",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPUPr7V5Cpug9I2nvVd6fhMEdfKhVxUpyZbmvVIwLTBA&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "5.9/10" }],
    imdbRating: "5.9",
    Type: "movie",
    BoxOffice: "$130,000,000"
  },
  {
    imdbID: "tt3",
    Title: "Dangal",
    Year: "2016",
    Rated: "U",
    Released: "21 Dec 2016",
    Runtime: "161 min",
    Genre: "Action, Biography, Drama",
    Director: "Nitesh Tiwari",
    Writer: "Piyush Gupta, Shreyas Jain, Nikhil Mehrotra",
    Actors: "Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh",
    Plot: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.",
    Language: "Hindi",
    Country: "India",
    Awards: "23 wins & 6 nominations",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrAj3X3l8pHj2TRRj7XL_6dz-pzxXeM6fZfKxhESWAKXnDJUMv7rA8BwMIbJSsfSHpHWrh&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.3/10" }],
    imdbRating: "8.3",
    Type: "movie",
    BoxOffice: "$330,000,000"
  },
  {
    imdbID: "tt4",
    Title: "Oppenheimer",
    Year: "2023",
    Rated: "R",
    Released: "21 Jul 2023",
    Runtime: "180 min",
    Genre: "Biography, Drama, History",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan, Kai Bird, Martin Sherwin",
    Actors: "Cillian Murphy, Emily Blunt, Matt Damon",
    Plot: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 7 Oscars. 333 wins & 385 nominations total",
    Poster: "https://wsrv.nl/?url=image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.3/10" }],
    imdbRating: "8.3",
    Type: "movie",
    BoxOffice: "$964,464,185"
  },
  {
    imdbID: "tt5",
    Title: "Dune: Part Two",
    Year: "2024",
    Rated: "PG-13",
    Released: "01 Mar 2024",
    Runtime: "166 min",
    Genre: "Action, Adventure, Drama",
    Director: "Denis Villeneuve",
    Writer: "Denis Villeneuve, Jon Spaihts, Frank Herbert",
    Actors: "Timothée Chalamet, Zendaya, Rebecca Ferguson",
    Plot: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    Language: "English",
    Country: "United States, Canada",
    Awards: "1 win",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHtBGsnxOoEQAsboEspaPoElQT-Z4wtTikQ45Hrb3x_6NvjOw607ZrPxk&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.6/10" }],
    imdbRating: "8.6",
    Type: "movie",
    BoxOffice: "$711,844,358"
  },
  {
    imdbID: "tt6",
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 157 wins & 220 nominations total",
    Poster: "https://wsrv.nl/?url=image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    imdbRating: "8.8",
    Type: "movie",
    BoxOffice: "$839,030,630"
  },
  {
    imdbID: "tt7",
    Title: "3 Idiots",
    Year: "2009",
    Rated: "UA",
    Released: "25 Dec 2009",
    Runtime: "170 min",
    Genre: "Comedy, Drama",
    Director: "Rajkumar Hirani",
    Writer: "Rajkumar Hirani, Abhijat Joshi, Chetan Bhagat",
    Actors: "Aamir Khan, Madhavan, Mona Singh",
    Plot: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
    Language: "Hindi, English",
    Country: "India",
    Awards: "66 wins & 24 nominations",
    Poster: "https://xvihiyosenhiwfgslfex.supabase.co/storage/v1/object/public/story-images/blog-images/1752325810588-eufpoihoaxs.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.4/10" }],
    imdbRating: "8.4",
    Type: "movie",
    BoxOffice: "$65,341,200"
  },
  {
    imdbID: "tt8",
    Title: "The Batman",
    Year: "2022",
    Rated: "PG-13",
    Released: "04 Mar 2022",
    Runtime: "176 min",
    Genre: "Action, Crime, Drama",
    Director: "Matt Reeves",
    Writer: "Matt Reeves, Peter Craig, Bob Kane",
    Actors: "Robert Pattinson, Zoë Kravitz, Jeffrey Wright",
    Plot: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    Language: "English, Spanish, Latin",
    Country: "United States",
    Awards: "Nominated for 3 Oscars. 39 wins & 165 nominations total",
    Poster: "https://wsrv.nl/?url=image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "7.8/10" }],
    imdbRating: "7.8",
    Type: "movie",
    BoxOffice: "$771,061,112"
  },
  {
    imdbID: "tt9",
    Title: "K.G.F: Chapter 2",
    Year: "2022",
    Rated: "UA",
    Released: "14 Apr 2022",
    Runtime: "168 min",
    Genre: "Action, Crime, Drama",
    Director: "Prashanth Neel",
    Writer: "Prashanth Neel",
    Actors: "Yash, Sanjay Dutt, Raveena Tandon",
    Plot: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order.",
    Language: "Kannada",
    Country: "India",
    Awards: "10 wins & 7 nominations",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToJ2MUilZyw-kpIINa_0uJmSdXQKFST9JML9khc73A6dJllEDuuPvLuITl&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.3/10" }],
    imdbRating: "8.3",
    Type: "movie",
    BoxOffice: "$160,000,000"
  },
  {
    imdbID: "tt10",
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Language: "English",
    Country: "United States, United Kingdom, Canada",
    Awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSkUqb-86cLqozgook0Yj9QkHHAiSEqNGoHe3CgZYIrjuH8fOVC0kcKexd&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.7/10" }],
    imdbRating: "8.7",
    Type: "movie",
    BoxOffice: "$733,802,604"
  },
  {
    imdbID: "tt11",
    Title: "Mirzapur: The Movie",
    Year: "2026",
    Rated: "A",
    Released: "2026",
    Runtime: "150 min",
    Genre: "Action, Crime, Drama",
    Director: "Gurmmeet Singh",
    Writer: "Puneet Krishna, Vineet Krishna",
    Actors: "Pankaj Tripathi, Ali Fazal, Divyenndu",
    Plot: "The cinematic continuation of the epic saga of power, revenge, and politics in the lawless city of Mirzapur.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQczGEJAOLiR5kNBAqH0P-inJSG_VvBvKQt9vJg9CqvVu5Omy4mQUJfjjw&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.9/10" }],
    imdbRating: "8.9",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt12",
    Title: "Spider-Man: Brand New Day",
    Year: "2026",
    Rated: "PG-13",
    Released: "2026",
    Runtime: "145 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Destin Daniel Cretton",
    Writer: "Chris McKenna, Erik Sommers",
    Actors: "Tom Holland, Zendaya",
    Plot: "Following the events of No Way Home, Peter Parker navigates his new life in New York City, forgotten by those he loves, while a new threat emerges.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster: "https://thumb.wikimedia.org/wikipedia/en/thumb/9/9a/Spider-Man_Brand_New_Day_poster.jpg/250px-Spider-Man_Brand_New_Day_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.5/10" }],
    imdbRating: "8.5",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt13",
    Title: "Toxic: A Fairy Tale for Grown-ups",
    Year: "2026",
    Rated: "A",
    Released: "10 Apr 2026",
    Runtime: "160 min",
    Genre: "Action, Drama, Thriller",
    Director: "Geetu Mohandas",
    Writer: "Geetu Mohandas",
    Actors: "Yash, Kiara Advani",
    Plot: "An action-packed fairy tale for grown-ups exploring the dark and gritty underworld.",
    Language: "Kannada, Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvWdzW_cy6B25hkoydXRjTPC0ZKNoB6US8RcsOCCAB01I9WnLyzNvyf_w&s=10",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    imdbRating: "8.8",
    Type: "movie",
    BoxOffice: "N/A"
  }
,
  {
    imdbID: "tt14",
    Title: "Dhurandhar",
    Year: "2024",
    Rated: "UA",
    Released: "N/A",
    Runtime: "120 min",
    Genre: "Action, Comedy",
    Director: "Unknown",
    Writer: "Unknown",
    Actors: "Local Stars",
    Plot: "A popular entry in the Action genre.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMmEzMzM1OGMtMDVkYS00NGMwLTgyNzAtZjgyNWU4NTlhZDc4XkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt15",
    Title: "Dhurandhar 2",
    Year: "2025",
    Rated: "UA",
    Released: "N/A",
    Runtime: "120 min",
    Genre: "Action, Comedy",
    Director: "Unknown",
    Writer: "Unknown",
    Actors: "Local Stars",
    Plot: "The sequel to Dhurandhar.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BNzdkNjAxNWMtNWY3My00NTI1LTg2YWQtOGI3MDA0NzdhMjEyXkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt16",
    Title: "Godari Gattupaina",
    Year: "2026",
    Rated: "UA",
    Released: "N/A",
    Runtime: "120 min",
    Genre: "Drama, Romance",
    Director: "Unknown",
    Writer: "Unknown",
    Actors: "Telugu Stars",
    Plot: "A popular entry in the Drama genre.",
    Language: "Telugu",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BOTcxNTRhMTItN2YzNS00ODhmLWIzODUtNTFiNmU1Yzg3Njc1XkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt17",
    Title: "https://m.media-amazon.com/images/M/MV5BOTcxNTRhMTItN2YzNS00ODhmLWIzODUtNTFiNmU1Yzg3Njc1XkEyXkFqcGc@._V1_.jpg",
    Year: "2021",
    Rated: "UA",
    Released: "N/A",
    Runtime: "179 min",
    Genre: "Action, Crime, Drama",
    Director: "Sukumar",
    Writer: "Sukumar",
    Actors: "Allu Arjun, Fahadh Faasil, Rashmika Mandanna",
    Plot: "A laborer rises through the ranks of a red sandalwood smuggling syndicate.",
    Language: "Telugu",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-hTPOBe2vBxZ9Co1q-Aw2PnU7hycdQXqD8Fbd6fJKZqTwTjWcIFrV5t8&s=10",
    Ratings: [{ Source: "IMDb", Value: "7.6/10" }],
    imdbRating: "7.6",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt18",
    Title: "Pushpa 2: The Rule",
    Year: "2024",
    Rated: "UA",
    Released: "N/A",
    Runtime: "180 min",
    Genre: "Action, Crime, Thriller",
    Director: "Sukumar",
    Writer: "Sukumar",
    Actors: "Allu Arjun, Fahadh Faasil, Rashmika Mandanna",
    Plot: "The sequel to Pushpa: The Rise.",
    Language: "Telugu",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcBc86YlOMFJz_rGeYh08BnuiiwNuAGiO71ez3-BQj9Q&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt19",
    Title: "Animal",
    Year: "2023",
    Rated: "A",
    Released: "N/A",
    Runtime: "201 min",
    Genre: "Action, Crime, Drama",
    Director: "Sandeep Reddy Vanga",
    Writer: "Sandeep Reddy Vanga",
    Actors: "Ranbir Kapoor, Anil Kapoor, Bobby Deol",
    Plot: "A son's love for his father becomes an obsession.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSioUet_1Mc9CmQZMp0EpxmZxyAKjChiteHqVpCdQS3MDXegSiQ8iTnItu0&s=10",
    Ratings: [{ Source: "IMDb", Value: "6.2/10" }],
    imdbRating: "6.2",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt20",
    Title: "Game Changer",
    Year: "2024",
    Rated: "UA",
    Released: "N/A",
    Runtime: "160 min",
    Genre: "Action, Drama, Thriller",
    Director: "S. Shankar",
    Writer: "Karthik Subbaraj",
    Actors: "Ram Charan, Kiara Advani",
    Plot: "An IAS officer aims to combat corrupt politicians by advocating for fair elections.",
    Language: "Telugu",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhsclKXyk1OENSPRasHMSpdFdVuRibZLx-A9PFZ1Sx37oPbSf57pPFp8SJ&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt21",
    Title: "Marco",
    Year: "2024",
    Rated: "UA",
    Released: "N/A",
    Runtime: "120 min",
    Genre: "Action, Thriller",
    Director: "Haneef Adeni",
    Writer: "Haneef Adeni",
    Actors: "Unni Mukundan",
    Plot: "A popular entry in the Action genre.",
    Language: "Malayalam",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMDQwMDIzN2ItNTI4Yy00ZTYzLTgwMTItN2ZlYjg3NTFlOTBlXkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt22",
    Title: "My Fault (Culpa Mia)",
    Year: "2023",
    Rated: "A",
    Released: "N/A",
    Runtime: "117 min",
    Genre: "Romance, Drama",
    Director: "Domingo González",
    Writer: "Mercedes Ron",
    Actors: "Nicole Wallace, Gabriel Guevara",
    Plot: "Noah has to leave her town, boyfriend and friends to move into her mom's new husband's mansion.",
    Language: "Spanish",
    Country: "Spain",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOUAi3zv4aoF2LOPpo6f81cE3_BgrB39qz_t8WC3t71A&s=10",
    Ratings: [{ Source: "IMDb", Value: "6.2/10" }],
    imdbRating: "6.2",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt23",
    Title: "Your Fault (Culpa Tuya)",
    Year: "2024",
    Rated: "A",
    Released: "N/A",
    Runtime: "120 min",
    Genre: "Romance, Drama",
    Director: "Domingo González",
    Writer: "Mercedes Ron",
    Actors: "Nicole Wallace, Gabriel Guevara",
    Plot: "The love between Noah and Nick seems unwavering despite the maneuvering of their parents.",
    Language: "Spanish",
    Country: "Spain",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdblg1uTvJjcbISihpRG0pZzeBZC_WRX8rFDQQJSQDLQ&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt24",
    Title: "Our Fault (Culpa Nuestra)",
    Year: "2025",
    Rated: "A",
    Released: "N/A",
    Runtime: "120 min",
    Genre: "Romance, Drama",
    Director: "Domingo González",
    Writer: "Mercedes Ron",
    Actors: "Nicole Wallace, Gabriel Guevara",
    Plot: "The finale to the Culpa Mia series.",
    Language: "Spanish",
    Country: "Spain",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnxp26w51a5yM-joynDo1OiStVzT-9cL4M7AWfar4X0Q&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt25",
    Title: "War",
    Year: "2019",
    Rated: "UA",
    Released: "N/A",
    Runtime: "154 min",
    Genre: "Action, Thriller",
    Director: "Siddharth Anand",
    Writer: "Aditya Chopra",
    Actors: "Hrithik Roshan, Tiger Shroff",
    Plot: "An Indian soldier is assigned to eliminate his former mentor.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhUsTuDrCbQsaBO926xoXwXS36xt9SwL32haHBzsW_8_AdXhagWE_ru5ua&s=10",
    Ratings: [{ Source: "IMDb", Value: "6.5/10" }],
    imdbRating: "6.5",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt26",
    Title: "War 2",
    Year: "2025",
    Rated: "UA",
    Released: "N/A",
    Runtime: "150 min",
    Genre: "Action, Thriller",
    Director: "Ayan Mukerji",
    Writer: "Aditya Chopra",
    Actors: "Hrithik Roshan, Jr. NTR",
    Plot: "Sequel to War (2019).",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnxp26w51a5yM-joynDo1OiStVzT-9cL4M7AWfar4X0Q&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt27",
    Title: "Fighter",
    Year: "2024",
    Rated: "UA",
    Released: "N/A",
    Runtime: "166 min",
    Genre: "Action, Thriller",
    Director: "Siddharth Anand",
    Writer: "Siddharth Anand",
    Actors: "Hrithik Roshan, Deepika Padukone",
    Plot: "Top IAF aviators come together in the face of imminent danger.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://i.pinimg.com/736x/cc/61/68/cc61688a82c5ce7a5de92e11cd85646f.jpg",
    Ratings: [{ Source: "IMDb", Value: "6.5/10" }],
    imdbRating: "6.5",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt28",
    Title: "12th Fail",
    Year: "2023",
    Rated: "U",
    Released: "N/A",
    Runtime: "147 min",
    Genre: "Biography, Drama",
    Director: "Vidhu Vinod Chopra",
    Writer: "Vidhu Vinod Chopra",
    Actors: "Vikrant Massey, Medha Shankar",
    Plot: "The real-life story of IPS Officer Manoj Kumar Sharma.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkTMUXGbny8ZjxH784XqVDOvjv56_J0cj-41LGMY-ibdybVT1fREXRKIV5&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.9/10" }],
    imdbRating: "8.9",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt29",
    Title: "Venom: The Last Dance",
    Year: "2024",
    Rated: "PG-13",
    Released: "N/A",
    Runtime: "110 min",
    Genre: "Action, Sci-Fi",
    Director: "Kelly Marcel",
    Writer: "Kelly Marcel",
    Actors: "Tom Hardy",
    Plot: "Eddie and Venom are on the run.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://wsrv.nl/?url=image.tmdb.org/t/p/w500/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
    Ratings: [{ Source: "IMDb", Value: "6.2/10" }],
    imdbRating: "6.2",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt30",
    Title: "Furious 7",
    Year: "2015",
    Rated: "PG-13",
    Released: "N/A",
    Runtime: "137 min",
    Genre: "Action, Thriller",
    Director: "James Wan",
    Writer: "Chris Morgan",
    Actors: "Vin Diesel, Paul Walker",
    Plot: "Deckard Shaw seeks revenge against Dominic Toretto.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://www.tallengestore.com/cdn/shop/products/Fast_Furious_7_-_Paul_Walker_-_Vin_Diesel_-_Dwayne_Johnson_-_Hollywood_Action_Movie_Poster_dc9198b7-c29f-4725-910c-366cef8dc546.jpg?v=1582543223",
    Ratings: [{ Source: "IMDb", Value: "7.1/10" }],
    imdbRating: "7.1",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt31",
    Title: "The Fate of the Furious (Fast 8)",
    Year: "2017",
    Rated: "PG-13",
    Released: "N/A",
    Runtime: "136 min",
    Genre: "Action, Crime",
    Director: "F. Gary Gray",
    Writer: "Chris Morgan",
    Actors: "Vin Diesel, Dwayne Johnson",
    Plot: "When a mysterious woman seduces Dom into the world of terrorism.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDDkHHoZrc08gFseRQj8UiQ7yfuaxUCgvqpgHI9mlS_NCkHorCaSiu1Hk&s=10",
    Ratings: [{ Source: "IMDb", Value: "6.6/10" }],
    imdbRating: "6.6",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt32",
    Title: "F9: The Fast Saga",
    Year: "2021",
    Rated: "PG-13",
    Released: "N/A",
    Runtime: "143 min",
    Genre: "Action, Crime",
    Director: "Justin Lin",
    Writer: "Daniel Casey",
    Actors: "Vin Diesel, John Cena",
    Plot: "Dom and the crew must take on an international terrorist.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSioQDtfyFDyBmeExG1apU9OMfe7C2qj_5qoiw19eSHEjLfp_NbGWD8nvBc&s=10",
    Ratings: [{ Source: "IMDb", Value: "5.2/10" }],
    imdbRating: "5.2",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt33",
    Title: "Fast X",
    Year: "2023",
    Rated: "PG-13",
    Released: "N/A",
    Runtime: "141 min",
    Genre: "Action, Crime",
    Director: "Louis Leterrier",
    Writer: "Dan Mazeau",
    Actors: "Vin Diesel, Jason Momoa",
    Plot: "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0ouVIUr6BU50a-LQCWgxtVkjxt1GrEbITzRrc2DUD6Ejra_hYUdIOdqQ&s=10",
    Ratings: [{ Source: "IMDb", Value: "5.8/10" }],
    imdbRating: "5.8",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt34",
    Title: "Money Heist",
    Year: "2017-2021",
    Rated: "A",
    Released: "N/A",
    Runtime: "70 min",
    Genre: "Action, Crime, Drama",
    Director: "Álex Pina",
    Writer: "Álex Pina",
    Actors: "Úrsula Corberó, Álvaro Morte",
    Plot: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history.",
    Language: "Spanish",
    Country: "Spain",
    Awards: "N/A",
    Poster: "https://wsrv.nl/?url=image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    Ratings: [{ Source: "IMDb", Value: "8.2/10" }],
    imdbRating: "8.2",
    Type: "series",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt35",
    Title: "The Boys",
    Year: "2019-",
    Rated: "A",
    Released: "N/A",
    Runtime: "60 min",
    Genre: "Action, Comedy, Crime",
    Director: "Eric Kripke",
    Writer: "Eric Kripke",
    Actors: "Karl Urban, Jack Quaid",
    Plot: "A group of vigilantes set out to take down corrupt superheroes.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB780ApzANMWpGYE3zKxYa8eQR0yspb2HdYkUT4bGizQ&s",
    Ratings: [{ Source: "IMDb", Value: "8.7/10" }],
    imdbRating: "8.7",
    Type: "series",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt36",
    Title: "Dragon Ball Super: Super Hero",
    Year: "2022",
    Rated: "PG-13",
    Released: "N/A",
    Runtime: "100 min",
    Genre: "Animation, Action",
    Director: "Tetsuro Kodama",
    Writer: "Akira Toriyama",
    Actors: "Masako Nozawa, Toshio Furukawa",
    Plot: "The Red Ribbon Army is back with new androids.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster: "https://wsrv.nl/?url=image.tmdb.org/t/p/w500/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
    Ratings: [{ Source: "IMDb", Value: "7.1/10" }],
    imdbRating: "7.1",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt37",
    Title: "Death Note",
    Year: "2006-2007",
    Rated: "A",
    Released: "N/A",
    Runtime: "24 min",
    Genre: "Animation, Crime, Drama",
    Director: "Tetsurō Araki",
    Writer: "Tsugumi Ohba",
    Actors: "Mamoru Miyano, Kappei Yamaguchi",
    Plot: "An intelligent high school student goes on a secret crusade to eliminate criminals.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTUwOTgzMTEyOF5BMl5BanBnXkFtZTgwNTk3MTM5MjI@._V1_FMjpg_UX1000_.jpg",
    Ratings: [{ Source: "IMDb", Value: "9.0/10" }],
    imdbRating: "9.0",
    Type: "series",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt38",
    Title: "Stand by Me Doraemon",
    Year: "2014",
    Rated: "U",
    Released: "N/A",
    Runtime: "95 min",
    Genre: "Animation, Comedy, Family",
    Director: "Tony Oliver",
    Writer: "Takashi Yamazaki",
    Actors: "Wasabi Mizuta",
    Plot: "Doraemon comes to help Nobita.",
    Language: "Japanese, Hindi",
    Country: "Japan",
    Awards: "N/A",
    Poster: "https://i.pinimg.com/736x/12/72/62/127262a0f2fd8701462adcf35283329f.jpg",
    Ratings: [{ Source: "IMDb", Value: "7.4/10" }],
    imdbRating: "7.4",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt39",
    Title: "Ben 10",
    Year: "2005-2008",
    Rated: "U",
    Released: "N/A",
    Runtime: "22 min",
    Genre: "Animation, Action, Sci-Fi",
    Director: "Scooter Tidwell",
    Writer: "Man of Action",
    Actors: "Tara Strong",
    Plot: "A boy discovers an alien watch that gives him powers.",
    Language: "English, Hindi",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://theworldofnerds.com/cdn/shop/files/61.png?v=1771398134&width=1946",
    Ratings: [{ Source: "IMDb", Value: "7.5/10" }],
    imdbRating: "7.5",
    Type: "series",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt40",
    Title: "Pokémon: The First Movie",
    Year: "1998",
    Rated: "U",
    Released: "N/A",
    Runtime: "96 min",
    Genre: "Animation, Action, Adventure",
    Director: "Kunihiko Yuyama",
    Writer: "Takeshi Shudo",
    Actors: "Veronica Taylor",
    Plot: "Ash and friends must stop Mewtwo.",
    Language: "Japanese, English",
    Country: "Japan",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShgJI09AxKq2yKzHbY8vqpun2La-aNneWLoO9CjZ3Mo95HaLsFG7qRQ4Y&s=10",
    Ratings: [{ Source: "IMDb", Value: "6.2/10" }],
    imdbRating: "6.2",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt41",
    Title: "Crayon Shin-chan",
    Year: "1992-",
    Rated: "UA",
    Released: "N/A",
    Runtime: "24 min",
    Genre: "Animation, Comedy",
    Director: "Mitsuru Hongo",
    Writer: "Yoshito Usui",
    Actors: "Akiko Yajima",
    Plot: "The adventures of a mischievous 5-year-old.",
    Language: "Japanese, Hindi",
    Country: "Japan",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpA-syK8yXkb0FUbYrHqMp-lCJ_CTYOb_neBDdV5Q4CPjqHqARYZMUOR0&s=10",
    Ratings: [{ Source: "IMDb", Value: "8.0/10" }],
    imdbRating: "8.0",
    Type: "series",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt42",
    Title: "Bhagam Bhag",
    Year: "2006",
    Rated: "UA",
    Released: "N/A",
    Runtime: "159 min",
    Genre: "Comedy, Mystery",
    Director: "Priyadarshan",
    Writer: "Neeraj Vora",
    Actors: "Akshay Kumar, Govinda, Paresh Rawal",
    Plot: "Members of a theatre group get framed for a murder.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjIyNmJjMDYtNTFjOS00NDA0LWI1NTMtNjc5NDRkZWQ2NjMyXkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "6.5/10" }],
    imdbRating: "6.5",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt43",
    Title: "Phir Hera Pheri",
    Year: "2006",
    Rated: "U",
    Released: "N/A",
    Runtime: "153 min",
    Genre: "Comedy",
    Director: "Neeraj Vora",
    Writer: "Neeraj Vora",
    Actors: "Akshay Kumar, Suniel Shetty, Paresh Rawal",
    Plot: "Baburao, Raju and Shyam are living happily after having risen from rags to riches.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTNkZTExMWYtMGZjMy00NGUwLWJmMWEtOThjYmZjY2Q0N2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    Ratings: [{ Source: "IMDb", Value: "7.2/10" }],
    imdbRating: "7.2",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt44",
    Title: "Chup Chup Ke",
    Year: "2006",
    Rated: "U",
    Released: "N/A",
    Runtime: "164 min",
    Genre: "Comedy, Drama",
    Director: "Priyadarshan",
    Writer: "Neeraj Vora",
    Actors: "Shahid Kapoor, Kareena Kapoor",
    Plot: "A debt-ridden young man attempts suicide, but is rescued only to find that his luck is finally turning.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRETpJfw40-pI-LDyQvSzzqrgnqa8Nnaa1KgFBo2jc32VNTKb8Elr3YSMfl&s=10",
    Ratings: [{ Source: "IMDb", Value: "6.9/10" }],
    imdbRating: "6.9",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt45",
    Title: "Welcome",
    Year: "2007",
    Rated: "UA",
    Released: "N/A",
    Runtime: "159 min",
    Genre: "Comedy, Crime",
    Director: "Anees Bazmee",
    Writer: "Anees Bazmee",
    Actors: "Akshay Kumar, Katrina Kaif, Nana Patekar",
    Plot: "Two thugs try to fix their sister's wedding.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_nLUtD9IbAmuyf2gAyuJ_IW_vjlGSvGFOJ4I8Wwmgog&s=10",
    Ratings: [{ Source: "IMDb", Value: "7.0/10" }],
    imdbRating: "7.0",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt46",
    Title: "Khatta Meetha",
    Year: "2010",
    Rated: "U",
    Released: "N/A",
    Runtime: "157 min",
    Genre: "Comedy, Drama",
    Director: "Priyadarshan",
    Writer: "Priyadarshan",
    Actors: "Akshay Kumar, Trisha Krishnan",
    Plot: "A struggling road construction contractor faces challenges.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjE1NjI0MTUxMF5BMl5BanBnXkFtZTcwNjg3NDE3Mw@@._V1_FMjpg_UX1000_.jpg",
    Ratings: [{ Source: "IMDb", Value: "5.8/10" }],
    imdbRating: "5.8",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt47",
    Title: "De Dana Dan",
    Year: "2009",
    Rated: "UA",
    Released: "N/A",
    Runtime: "167 min",
    Genre: "Comedy, Crime",
    Director: "Priyadarshan",
    Writer: "Suresh Krissna",
    Actors: "Akshay Kumar, Katrina Kaif",
    Plot: "Two broke friends kidnap a dog to get rich.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMGU3MDg5M2UtY2M5OC00NDE2LWIxYjEtMmVjNzIwMjZmNDYyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    Ratings: [{ Source: "IMDb", Value: "5.8/10" }],
    imdbRating: "5.8",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt48",
    Title: "Bhool Bhulaiyaa",
    Year: "2007",
    Rated: "UA",
    Released: "N/A",
    Runtime: "159 min",
    Genre: "Comedy, Horror",
    Director: "Priyadarshan",
    Writer: "Neeraj Vora",
    Actors: "Akshay Kumar, Vidya Balan",
    Plot: "An NRI and his wife stay in an ancestral home despite ghost warnings.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BNGI1Y2UwNmQtMmE4MS00ZmVhLTg3YzgtYTg3NGUzOTI5NjdjXkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "7.4/10" }],
    imdbRating: "7.4",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt49",
    Title: "Entertainment",
    Year: "2014",
    Rated: "U",
    Released: "N/A",
    Runtime: "140 min",
    Genre: "Comedy",
    Director: "Sajid-Farhad",
    Writer: "Sajid-Farhad",
    Actors: "Akshay Kumar, Tamannaah Bhatia",
    Plot: "A man tries to inherit wealth, but discovers a dog is the heir.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BNTY4ZmQ4NmEtZmM2ZC00ZDViLWFmY2ItMjc4ZGE1YTJkNWU3XkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "4.5/10" }],
    imdbRating: "4.5",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt50",
    Title: "Dhol",
    Year: "2007",
    Rated: "UA",
    Released: "N/A",
    Runtime: "145 min",
    Genre: "Comedy, Thriller",
    Director: "Priyadarshan",
    Writer: "Priyadarshan",
    Actors: "Tusshar Kapoor, Sharman Joshi",
    Plot: "Four lazy friends try to woo their rich neighbor.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BYzk3MDk1NzEtMzI4Yy00YmVhLTg3NzUtYjhlMTJkM2VhZGEwXkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "6.4/10" }],
    imdbRating: "6.4",
    Type: "movie",
    BoxOffice: "N/A"
  },
  {
    imdbID: "tt51",
    Title: "Dhamaal",
    Year: "2007",
    Rated: "U",
    Released: "N/A",
    Runtime: "136 min",
    Genre: "Comedy, Action",
    Director: "Indra Kumar",
    Writer: "Paritosh Painter",
    Actors: "Sanjay Dutt, Riteish Deshmukh, Arshad Warsi",
    Plot: "Four lazy slackers learn about a hidden treasure.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BZWU3OTEzODgtMWY4OS00N2NkLWJlNGQtMWZhZDJmODQwN2E5XkEyXkFqcGc@._V1_.jpg",
    Ratings: [{ Source: "IMDb", Value: "7.4/10" }],
    imdbRating: "7.4",
    Type: "movie",
    BoxOffice: "N/A"
  }
];

// We directly use the INITIAL_MOVIES array as our database.
// This way, any changes you make to the 'Poster' links or movie details above 
// will instantly show up in the browser without needing to clear Local Storage.
const getDatabase = () => {
  return INITIAL_MOVIES;
};

// Simulate network latency for realism
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

export const searchMovies = async (query = '', page = 1, category = 'All') => {
  console.log(`[Backend System] Querying database for: "${query}", Category: ${category}, Page: ${page}...`);
  await sleep(650); // Simulate network/DB latency
  
  const moviesDB = getDatabase();
  const lowerQuery = (query || '').toLowerCase().trim();
  
  // Advanced DB search simulation
  const results = moviesDB.filter(movie => {
    // Search match
    let matchesQuery = true;
    if (lowerQuery) {
      matchesQuery = movie.Title.toLowerCase().includes(lowerQuery) || 
                     movie.Genre.toLowerCase().includes(lowerQuery) ||
                     movie.Actors.toLowerCase().includes(lowerQuery) ||
                     movie.Director.toLowerCase().includes(lowerQuery);
    }
    
    // Category match
    let matchesCategory = true;
    if (category !== 'All') {
      if (category === 'Bollywood') matchesCategory = movie.Language.includes('Hindi');
      else if (category === 'Hollywood') matchesCategory = movie.Language.includes('English') && movie.Country.includes('United States');
      else matchesCategory = movie.Genre.includes(category);
    }
    
    return matchesQuery && matchesCategory;
  });

  const ITEMS_PER_PAGE = 10;
  const start = (page - 1) * ITEMS_PER_PAGE;
  const end = start + ITEMS_PER_PAGE;
  const paginatedResults = results.slice(start, end);

  if (paginatedResults.length > 0) {
    console.log(`[Backend System] 200 OK - Found ${results.length} results.`);
    return {
      Response: "True",
      Search: paginatedResults,
      totalResults: results.length.toString()
    };
  } else {
    console.warn(`[Backend System] 404 NOT FOUND - No records matched query: ${query}`);
    return {
      Response: "False",
      Error: "No movies found."
    };
  }
};

export const getMovieDetails = async (imdbId) => {
  if (!imdbId) return null;
  
  console.log(`[Backend System] Fetching record ID: ${imdbId} from database...`);
  await sleep(450); // Simulate network/DB latency

  const moviesDB = getDatabase();
  const movie = moviesDB.find(m => m.imdbID === imdbId);

  if (movie) {
    console.log(`[Backend System] 200 OK - Record retrieved successfully.`);
    return {
      Response: "True",
      ...movie
    };
  } else {
    console.error(`[Backend System] 500 ERROR - Record not found in database.`);
    return {
      Response: "False",
      Error: "Movie not found."
    };
  }
};

export const getRandomMovieId = () => {
  const moviesDB = getDatabase();
  const randomIndex = Math.floor(Math.random() * moviesDB.length);
  return moviesDB[randomIndex].imdbID;
};
